accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 로그인 페이지가 첫 페이지
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    # 로그인 후 처음 마주친는 첫 개인 페이지 - 닉네임으로 바꾸자
    path('<str:username>/', views.firstpage, name="firstpage"),

    # 여기부터는 내 정보 페이지
    path('<str:username>/mypage/', views.mypage, name="mypage"),
    # 회원정보수정
    path('<str:username>/mypage/myinfo_change/', views.myinfo_change, name="myinfo_change"),
    # 스크랩한 글 목록 조회
    path('<str:username>/mylist/', views.scrap, name="scrap"),
    
    # 내가 본 영화목록 조회 - 검색기능 탑재
    path('<str:username>/my_movie_list/', views.my_movie_list, name='my_movie_list'),

    # 내 영화 목록에 추가
    path('<str:username>/my_movie_list/add/<int:movie_pk>/', views.add_mymovie_list, name='add_mymovie_list'),

    # 내 영화 목록에서 제거
    path('<str:username>/my_movie_list/remove/<int:movie_pk>/', views.remove_mymovie_list, name='remove_mymovie_list'),

    # 일촌 목록 조회
    path('<str:username>/my_connection_list/', views.linkedin, name="linkedin"),

    # 여기부터는 일촌관련 내용

    # 일촌신청 메세지 보내기
    path('<str:username>/send_connected/', views.send_connected, name="send_connected"),
    # 일촌 수락하기 : to - page 주인 from - 신청한 사람
    path('<str:to_username>/connected/<str:from_username>/<int:send_connect_pk>/', views.connected_complete, name="connected_complete"),
    # 일촌평 작성
    path('visitor_book/<str:host>/<str:writer>/', views.visitor_book_create, name='visitor_book_create'),

]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

# static 등록을 위해 사용
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 관리자 페이지
    path('admin/', admin.site.urls),
    # 홈 화면 - 로그인 화면 로그인 후 넘어갈 화면 연결
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    # 영화추천 시스템 구축
    path('recommend/', views.recommend, name='recommend'),
]

movies/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    genres = models.TextField()
    nations = models.TextField()
    poster = models.CharField(max_length=300)
    content = models.TextField()

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth import get_user_model

from django.db.models import Count, Max, Min

from accounts.models import User
from .models import Movie



# Create your views here.
@require_GET
def index(request):
    movies = Movie.objects.all()
    # 영화 검색기능
    search_movie = request.GET.get('search_movie')
    # 사용자 정보 넘겨주기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)
    if search_movie:
        search_movie_list = movies.filter(title__icontains=search_movie)

    else:
        search_movie_list = '결과없음'

    context = {
        'search_movie': search_movie,
        'movies': movies,
        'search_movie_list': search_movie_list,
        'host_user': host_user,
    }
    return render(request, 'movies/index.html', context)


@require_GET
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    
    # 사용자 정보 넘겨주기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)

    context = {
        'movie': movie,
        'host_user': host_user,
    }
    return render(request, 'movies/detail.html', context)


def recommend(request):
    # 현재 로그인된 사용자 정보 가져오기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)

    # 내 일촌 중 일촌평 가장 많이 남긴 사람이 누구인지 가져오기
    who_is_my_best_friend = host_user.host_book.values('writer').annotate(count_book=Count('host')).order_by('-count_book').first()

    # 이를 바탕으로 사용자 인스턴스 가져와서 넘겨주기
    my_best_friend = get_object_or_404(get_user_model(), pk=who_is_my_best_friend['writer'])

    # my_best_friend =''

    context ={
        'my_best_friend': my_best_friend,
        'host_user': host_user,
    }
    '''        
    # 1. 로그인한 유저의 일촌에서 선호 영화 가져오기 - 3개정도만 보여주기

    # 2. 일촌정보 가져와서 일촌평 가장 많이 쓴 사람에서 평점 높은거 

    # 3. 스크랩한 글 가장 많은 작성자 선호영화 => 추천

    # 4. 1&2&3을 종합해서 추천
    '''


    return render(request, 'movies/recommend.html', context)

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
<div class="movie-list-form">
  <font style="font-size:10pt;">
  <font style="font-size:14pt"><p><strong>{{ movie.title }}</strong></p></font>
  <p><strong>장르:</strong> {{ movie.genres }}</p>
  <p><strong>감독:</strong> {{ movie.director }}</p>
  <p><strong>국가 :</strong> {{ movie.nations }}</p>
  <table>
    <tr>
      <td>
        <div><img src="{{ movie.poster }}" alt="" width="200px"></div>
      </td>
      {% comment %} <td witdh="20px"></td> {% endcomment %}
      <td padding="10px">
        <div>줄거리 : <br>{{ movie.content }}</div>
      </td>
    </tr>
  </table>
  
  
  
  
  <a type="button" class="logout_btn" href="{% url 'movies:index' %}">뒤로가기</a>
</font>
</div>
{% endblock middle %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
<br>
  <strong><font style="font-size:14pt;"><p class="text-center">영화 목록</p></font></strong>
    
    <!-- 영화검색 기능 -->
    <div class="movie-list-form" padding="10px" >
      <div>
      <input type="text" name="search_movie" placeholder="영화검색하기">
      <input class="logout_btn" type="submit" value="검색">
      <!-- 영화추천 받기 버튼 -->
      <br>
      <br>
      <div><strong><a class="btn btn-info btn-block text-white font-weight-bold" href="{% url 'movies:recommend' %}">영화 추천받기</a></strong></div>
      </div>
    </div>
    <!-- 검색했을 때 나올 결과 -->
    <div class="movie-list-form" style="display:flex;flex-wrap:wrap;">
    {% if search_movie %}
      <br>
      {% for movie in search_movie_list %}
        <font style="font-size:10pt;">
        <div class="text-center" style="display:flex;flex-direction:row;justify-content:center;">  
          <a href="{% url 'movies:detail' movie.pk %}">
            <div style="padding:1px;">
              <img style="padding:5px;" src="{{ movie.poster }}" alt="영화포스터" height="150px"><br>
              <strong>{{ movie.title|truncatechars:12 }}</strong>
            </div>
          </a> 
        </div>
        </font>
      {% endfor %}
    <!-- 전체 영화정보 나올 결과 -->
    {% else %}
      {% for movie in movies %}
        <font style="font-size:11pt;">
        <div class="text-center" style="display:flex;flex-direction:row;justify-content:center;">  
          <a href="{% url 'movies:detail' movie.pk %}">
          <div style="padding:1px;">
            <img style="padding:5px;" src="{{ movie.poster }}" alt="영화포스터" height="185px"><br>
            <strong>{{ movie.title|truncatechars:12 }}</strong>
          </div>
          </a> 
        </div>
        <br>
        </font>
      {% endfor %}
        <br>
    {% endif %}
    </div>

{% endblock middle %}
  

movies/templates/movies/recommend.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}


{% block middle %}
<br>
<strong><font style="font-size:14pt;"><p class="text-center">영화 추천</p></font></strong>
  {% comment %} <h1>추천영화페이지</h1> {% endcomment %}
   <font style="font-size:11pt;"><div class="movie-list-form">
   <div class="text-monospace">
      <p class="h5">이런 영화는 어때요?</p>
      <p class="h5">가장 많은 일촌평을 남긴 <span class="h4 font-weight-bold">{{ my_best_friend.nickname }}</span>님의 찜 목록입니다.</p>
    </div>
  </div></font>

  {% comment %} <form action=""></form>
    <form action="{% url "movies:recommend"%}">
      {% csrf_token %}
      <input type="submit" value="추천받기">
    </form>
  <hr> {% endcomment %}
  <!-- 추천 받았을 때 보여줄 요소들 -->
  <div class="movie-list-form" style="display:flex;flex-wrap:wrap;">
    <font style="font-size:10pt;">
      {% if my_best_friend %}
        {% with  movies=my_best_friend.mymovie.all  %}
          {% for movie in movies %}
          <!-- 여기는 내 영화목록에 저장 -->
          {% comment %} <div class="text-center" style="display:flex;flex-direction:row;">
            <a href="{% url 'movies:detail' movie.pk %}">
              <div style="padding:1px;">
                <img src="{{ movie.poster }}" alt="" height="150px"> </div>
                <div><strong>{{ movie.title|truncatechars:12 }}</strong></div>
             
            </a>
            <!-- 여기는 디테일 정보로 이동 -->
            
          </div> {% endcomment %}
             <div style="border:1px solid #C4CACD;margin:10px">
     <!-- 여기는 내 영화목록에 저장 -->
      {% comment %} <a href="{% url "accounts:add_mymovie_list" username movie.pk %}"> {% endcomment %}
      <div>
        <font style="font-size:12pt;"><strong><p>{{ movie.title }}</p></strong></font>
      </div>
      {% comment %} </a> {% endcomment %}
      <!-- 여기는 디테일 정보로 이동 -->
      <div style="display:flex;display-direction:row;justify-content:center">
        <div>
        <font style="font-size:10pt;">
          <a href="{% url 'movies:detail' movie.pk %}">
            <img style="margin:10px"src="{{ movie.poster }}" alt="" height="150px">
          </a>
        </div>
        
        <div>
        <br>
          <strong>{{ movie.genres }}</p></strong><p>
          <p display="flex-end" align="left" vertical-align="bottom text-bottom">{{ movie.content|truncatechars:130 }}<br></p> 
          <a valign="top" class="logout_btn submit-btn" href="{% url 'movies:detail' movie.pk %}">자세히 보기</a> 
          
        </div>
      </div>
      
        
          
      </font>
    </div>
          {% endfor %}
        {% endwith %}
      {% endif %}
    </font>
  </div>
 
{% endblock %}