accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 로그인 페이지가 첫 페이지
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    # 로그인 후 처음 마주친는 첫 개인 페이지 - 닉네임으로 바꾸자
    path('<str:username>/', views.firstpage, name="firstpage"),

    # 여기부터는 내 정보 페이지
    path('<str:username>/mypage/', views.mypage, name="mypage"),
    # 회원정보수정
    path('<str:username>/mypage/myinfo_change/', views.myinfo_change, name="myinfo_change"),
    # 스크랩한 글 목록 조회
    path('<str:username>/mylist/', views.scrap, name="scrap"),
    
    # 내가 본 영화목록 조회 - 검색기능 탑재
    path('<str:username>/my_movie_list/', views.my_movie_list, name='my_movie_list'),

    # 내 영화 목록에 추가
    path('<str:username>/my_movie_list/add/<int:movie_pk>/', views.add_mymovie_list, name='add_mymovie_list'),

    # 내 영화 목록에서 제거
    path('<str:username>/my_movie_list/remove/<int:movie_pk>/', views.remove_mymovie_list, name='remove_mymovie_list'),

    # 일촌 목록 조회
    path('<str:username>/my_connection_list/', views.linkedin, name="linkedin"),

    # 여기부터는 일촌관련 내용

    # 일촌신청 메세지 보내기
    path('<str:username>/send_connected/', views.send_connected, name="send_connected"),
    # 일촌 수락하기 : to - page 주인 from - 신청한 사람
    path('<str:to_username>/connected/<str:from_username>/<int:send_connect_pk>/', views.connected_complete, name="connected_complete"),
    # 일촌평 작성
    path('visitor_book/<str:host>/<str:writer>/', views.visitor_book_create, name='visitor_book_create'),

]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    # 전체 페이지 조회
    path('reviews/', views.index, name='index'),
    # 리뷰 생성하기
    path('reviews/create/', views.create, name='create'),
    # 리뷰 자세히 보기
    path('reviews/<int:review_pk>/', views.detail, name='detail'),
    # 리뷰 수정하기
    path('reviews/<int:review_pk>/update/', views.update, name='update'),
    # 리뷰 삭제
    path('reviews/<int:review_pk>/delete/', views.delete, name='delete'),

    # 리뷰에 댓글 달기
    path('reviews/<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    # 댓글 삭제
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    
    
    
    # 스크랩 요청 보내기
    path('reviews/<int:review_pk>/my_scrap_reviews/', views.user_scraped_reviews, name="user_scraped_reviews"),
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

# static 등록을 위해 사용
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 관리자 페이지
    path('admin/', admin.site.urls),
    # 홈 화면 - 로그인 화면 로그인 후 넘어갈 화면 연결
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    # 영화추천 시스템 구축
    path('recommend/', views.recommend, name='recommend'),
]

community/models.py
from django.db import models
from django.conf import settings

from django.core.validators import MaxValueValidator, MinValueValidator

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    # 평점 범위 설정
    rank = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 스크랩 필드
    scrap_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='scrap_reviews')


class Comment(models.Model):
    content = models.CharField(max_length=255)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods

from .models import Review, Comment
from .forms import ReviewForm, CommentForm

from django.db.models import Q


# 전체 리뷰 조회
@login_required
def index(request):
    reviews = Review.objects.order_by('-pk')

    # 리뷰 검색기능
    search_review = request.GET.get('search_review')

    # 사용자 정보 넘겨주기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)

    # 제목, 영화제목, 내용 포함해서 검색
    if search_review:
        search_review_list = reviews.filter(Q(title__icontains=search_review) | Q(content__icontains=search_review) | Q(movie_title__icontains=search_review))

    else:
        search_review_list = '결과없음'

    context = {
        'reviews': reviews,
        'search_review': search_review,
        'search_review_list': search_review_list,
        'host_user': host_user,
    }
    return render(request, 'community/index.html', context)


# 리뷰 작성
@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST) 
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()

    # 사용자 정보 넘기기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)

    context = {
        'form': form,
        'host_user': host_user,
    }
    return render(request, 'community/create.html', context)


# 세부 페이지 조회
@login_required
def detail(request, review_pk):
    
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    # 사용자 정보 넘기기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,
        'host_user': host_user,
    }
    return render(request, 'community/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('community:detail', review_pk)

    else:
        form = ReviewForm(instance=review)

    # 사용자 정보 넘기기
    host_user = get_object_or_404(get_user_model(), pk=request.user.pk)

    context = {
        'form': form,
        'review': review,
        'host_user': host_user,
    }

    return render(request, 'community/update.html', context)


@login_required
def delete(request, review_pk):
    # 로그인한 유저이면
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        review.delete()
    
    return redirect('community:index')


@login_required
def user_scraped_reviews(request, review_pk):
    
    # 인증된 유저인지 확인
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user
        
        # 이미 스크랩했다면 제거
        if review.scrap_users.filter(pk=user.pk).exists():
            review.scrap_users.remove(user)

        else:
            review.scrap_users.add(user)

        return redirect('community:detail', review_pk)


# 댓글 생성
@login_required
@require_http_methods(['GET', 'POST'])
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('community:detail', review_pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)


# 댓글 삭제
@login_required
def delete_comment(request, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('community:detail', review_pk)

community/templates/community/_user_comments.html
{% extends 'base.html' %}
{% block content %}

<h2>{{ user.username }}댓글</h2>
{% for comment in user.comment_set.all %}
  <div>{{ comment.content }}</div>

{% endfor %}

{% endblock content %}

community/templates/community/_user_reviews.html
{% extends 'base.html' %}
{% block content %}

<h2>{{ user.username }}리뷰</h2>
{% for review in user.review_set.all %}
  <div>{{ review.title }}</div>
{% endfor %}

{% endblock content %}

community/templates/community/create.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
<br>
  <strong><font style="font-size:14pt;"><p class="text-center">영화 리뷰 쓰기</p></font></strong>
  <div class="create-form">
    <form action=""></form>
    <form action="" method="POST">
      <font style="font-size:10pt;">
        {% csrf_token %}
        &nbsp;글 제목:&nbsp;&nbsp;&nbsp;{{ form.title }}
        <table>
          <td>영화 제목:{{ form.movie_title}}</td>
          <td>평점:{{ form.rank }}</td>
        </table>
        <table>
          <td><p>포스터 자리 자리</p></td>
          <td width="10px"></td>
          <td>내용: {{ form.content }}</td>
        </table>
        <font style="font-size:8pt;"><input class="logout_btn submit-btn" type="submit" value="리뷰작성"></font>
      </font>
    </form>
  </div>
    
  <a class="logout_btn back-btn" href="{% url 'community:index' %}">뒤로가기</a>
{% endblock middle %}

community/templates/community/detail.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
<div class="movie-list-form">
 <h2 class="text-center">{{ review.title }}</h2>
  <div padding="10px">
  <div font-size="14px" style="float:right;">
    <p><font>No: {{ review.pk }}</font>
    <!-- 꽉 찬 북마크 아이콘 -->
    {% if request.user in review.scrap_users.all %} 
      <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-bookmark-check-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4 0a2 2 0 0 0-2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4zm6.854 5.854a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
      </svg>
      <!-- 스크랩한 인원 수 -->
      ({{ review.scrap_users.all|length }})
    <!-- 비어있는 북마크 아이콘 -->
    {% else %}
      <svg text-align="left" width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-bookmark-check" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
        <path fill-rule="evenodd" d="M10.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
      </svg>
      <!-- 스크랩한 인원 수 -->
      ({{ review.scrap_users.all|length }})
    {% endif %}
    </p>
  </div>
  
    <strong><p><hr>영화 제목</p></strong> <div>{{ review.movie_title }}</div>
    <table>
      <td align="left" valign="top">
        <strong><p>내용 </p></strong><font style="font-size:10pt;"><div>{{ review.content }}</div></font>
      </td>
      <td width="10px"></td>
      
    </table>
  
  
  <br>
  <font style="font-size:11pt;">
  <strong><p>평점:</strong> {{ review.rank }}</p>
  <strong><p>작성 시각:</strong> {{ review.created_at }}</p>
  <strong><p>수정 시각:</strong>{{ review.updated_at }} </p></font>
  <hr>
  <!-- 작성자는 수정 삭제 보이고-->
  {% if request.user == review.user %}
    <a class="logout_btn submit-btn" href="{% url "community:update" review.pk %}">수정</a>
    <!-- 삭제 -->
    <form action=""></form>
    <form action="{% url "community:delete" review.pk %}" method="POST">
      {% csrf_token %}
      <input class="logout_btn submit-btn" type="submit" value="삭제">
    </form>
  <!-- 그 외는 스크랩 버튼이 보인다 -->
  {% else %}
    <!-- 스크랩 버튼 -->
    <font font-size="12px"><a class="logout_btn submit-btn" href="{% url "community:user_scraped_reviews" review.pk %}">스크랩</a></font>
  {% endif %}


  <!-- 댓글 부분 -->
  <br><br>
  <hr>
  <strong><p>댓글 목록
  {% if comments|length %}
    <span>({{ comments|length }})</span>
  </p></strong>
  <br>
  {% endif %}
  {% for comment in comments %}
      <div style="display:flex;display-direction:row">
        {{ comment.user }} - {{ comment.content }}
        <!-- 댓글 삭제 부분 댓글 작성자만 보이게 -->
        {% if request.user == comment.user %}
          <form></form>
          <form action="{% url "community:delete_comment" review.pk comment.pk %}" method="POST">
            <div >
            <div style="float:left;">{% csrf_token %}</div>
            <div><input class="logout_btn back-btn" type="submit" value="댓글 삭제"></div>
        {% endif %}
          </div>
        </form>
      </div>
      <hr>
    {% empty %}
      <p>첫 번째 댓글을 달아주세요!</p>
  {% endfor %}

  <!-- 댓글작성 -->
  {% if request.user.is_authenticated %}
    <form action=""></form>
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }} <!-- as_p 추가로 문제 해결-->
      <input class="logout_btn submit-btn" type="submit" value="댓글작성">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a type="button" class="logout_btn back-btn" href="{% url 'community:index' %}">뒤로가기</a>
  </div> 


</div>
 {% endblock  %}

community/templates/community/index.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
<br>

<strong><font style="font-size:14pt;"><p class="text-center">영화리뷰 HOME</p></font></strong>

<div class="movie-list-form">
<!-- 영화검색 기능 -->
  <input type="text" name="search_review" placeholder="리뷰검색">
  <input type="submit" class="logout_btn" value="검색">
</div>
<div class="movie-list-form">
{% if search_review %}
  {% for review in search_review_list %}
    <!-- 여기는 내 영화목록에 저장 -->
    <div class="movie-list-form2">
      <p>글 제목: {{ review.title |truncatechars:40}}</p>
      <!-- 여기는 디테일 정보로 이동 -->
      <div><a class="logout_btn submit-btn"href="{% url "community:detail" review.pk %}">자세히보기</a></div>
    </div>
  {% endfor %}
  <!-- 검색했을 때 결과의 총 개수 출력 -->
  <div style="padding: 10px;
	  margin: 10px;
	  width:520px;
	  float:left;">
    <p>검색결과는 총 <span>{{ search_review_list|length }}</span>개입니다</p>
  </div>

{% else %}
{% for review in reviews %}
  <div class="movie-list-form2">
  <font style="font-size:10pt;">

      <p>작성자 : {{ review.user }}</p>
      <p>글 번호: {{ review.pk }}</p>
      <p>글 제목: {{ review.title }}</p>
      <p>글 내용: {{ review.content |truncatechars:80}}</p>
      <div><a class="logout_btn submit-btn"href="{% url "community:detail" review.pk %}">자세히보기</a></div>

  </font>
 </div> 
{% endfor %}
{% endif %}
</div>
<!-- 검색했을 때 나올 결과 -->

{% endblock  %}

community/templates/community/update.html
{% extends 'base.html' %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}

{% block middle %}
  <h1 class="text-center">UPDATE</h1>
  <form action=""></form>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <font style="font-size:8pt;"><input class="logout_btn submit-btn" type="submit" value="리뷰수정"></font>
      </font>
  </form>
  <hr>
  <font style="font-size:8pt;"><a class="logout_btn" href="{% url 'community:detail' review.pk %}">뒤로가기</a></font>
{% endblock %}

community/templates/community/user_comments.html
{% extends 'base.html' %}
{% block content %}

<h2>{{ user.username }}댓글</h2>
{% for comment in user.comment_set.all %}
  <div>{{ comment.content }}</div>

{% endfor %}

{% endblock content %}

community/templates/community/user_reviews.html
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% block content %}

<h2>{{ user.username }}님의 리뷰</h2>
{% for review in user.review_set.all %}
  <a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a>
{% endfor %}

{% endblock content %}