accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 로그인 페이지가 첫 페이지
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    # 로그인 후 처음 마주친는 첫 개인 페이지 - 닉네임으로 바꾸자
    path('<str:username>/', views.firstpage, name="firstpage"),

    # 여기부터는 내 정보 페이지
    path('<str:username>/mypage/', views.mypage, name="mypage"),
    # 회원정보수정
    path('<str:username>/mypage/myinfo_change/', views.myinfo_change, name="myinfo_change"),
    # 스크랩한 글 목록 조회
    path('<str:username>/mylist/', views.scrap, name="scrap"),
    
    # 내가 본 영화목록 조회 - 검색기능 탑재
    path('<str:username>/my_movie_list/', views.my_movie_list, name='my_movie_list'),

    # 내 영화 목록에 추가
    path('<str:username>/my_movie_list/add/<int:movie_pk>/', views.add_mymovie_list, name='add_mymovie_list'),

    # 내 영화 목록에서 제거
    path('<str:username>/my_movie_list/remove/<int:movie_pk>/', views.remove_mymovie_list, name='remove_mymovie_list'),

    # 일촌 목록 조회
    path('<str:username>/my_connection_list/', views.linkedin, name="linkedin"),

    # 여기부터는 일촌관련 내용

    # 일촌신청 메세지 보내기
    path('<str:username>/send_connected/', views.send_connected, name="send_connected"),
    # 일촌 수락하기 : to - page 주인 from - 신청한 사람
    path('<str:to_username>/connected/<str:from_username>/<int:send_connect_pk>/', views.connected_complete, name="connected_complete"),
    # 일촌평 작성
    path('visitor_book/<str:host>/<str:writer>/', views.visitor_book_create, name='visitor_book_create'),

]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    # 전체 페이지 조회
    path('reviews/', views.index, name='index'),
    # 리뷰 생성하기
    path('reviews/create/', views.create, name='create'),
    # 리뷰 자세히 보기
    path('reviews/<int:review_pk>/', views.detail, name='detail'),
    # 리뷰 수정하기
    path('reviews/<int:review_pk>/update/', views.update, name='update'),
    # 리뷰 삭제
    path('reviews/<int:review_pk>/delete/', views.delete, name='delete'),

    # 리뷰에 댓글 달기
    path('reviews/<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    # 댓글 삭제
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    
    
    
    # 스크랩 요청 보내기
    path('reviews/<int:review_pk>/my_scrap_reviews/', views.user_scraped_reviews, name="user_scraped_reviews"),
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

# static 등록을 위해 사용
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 관리자 페이지
    path('admin/', admin.site.urls),
    # 홈 화면 - 로그인 화면 로그인 후 넘어갈 화면 연결
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    # 영화추천 시스템 구축
    path('recommend/', views.recommend, name='recommend'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# 내 영화목록을 만들기 위해 모델 불러오기
from movies.models import Movie


# 사용자 프로필 파일에 이름을 지어서 저장하자
def profile_img_path(instance, filename):
    # 저장할 주소는 BASE_DIR의 media/user_id/filename
    print(instance)
    return f'user_{instance}/{filename}'

# 사용자 모델에서 필요한 요소 - 아이디, 비밀번호, 닉네임, 이메일
class User(AbstractUser):
    email = models.EmailField(
        # 관리자페이지에서 보여질 부분
        verbose_name = '이메일',
        max_length = 255,
        unique = True,
    )
    nickname = models.CharField(
        verbose_name = '닉네임',
        max_length = 30,
        unique=True,
    )
    greetings = models.CharField(
        verbose_name= '인사말',
        max_length= 50,
        null = True, 
        blank = True,
    )
    # 일촌 필드
    connected = models.ManyToManyField('self', symmetrical=True)
    # 프로필이미지필드 추가 - 빈값으로 생성가능하고, 빈 폼도 제출가능
    # 사진 들어가는 것 확인하고 blank=True로 변경
    profile_img = models.ImageField(
        null = True, 
        blank = True,
        verbose_name = '프로필사진',
        upload_to = profile_img_path
        )

    # 나의 영화리스트
    mymovie = models.ManyToManyField(Movie)
    

# 일촌 신청 테이블 (누가, 누구한테, 신청수락여부)로 구성
class SendConnect(models.Model):
    # 요청을 보낸 사용자 아이디
    give_user = models.CharField(max_length=255)
    # 요청을 받은 사용자 아이디
    take_user = models.CharField(max_length=255)
    # 요청을 수락한다면 테이블에서 지우자 - 생성시 true로
    sure = models.BooleanField(default=True)


# 일촌들의 방명록 작성 
# 내용 작성일, 페이지주인, 작성자, 생성일, 수정일
class VisitorBook(models.Model):
    content = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 일촌평의 주인은 1명 - 게시글은 여러개
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='host_book')
    # 작성자 id 정보를 저장할 것이기 때문에 반대에서는 소유자
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='writer_book')

community/models.py
from django.db import models
from django.conf import settings

from django.core.validators import MaxValueValidator, MinValueValidator

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    # 평점 범위 설정
    rank = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 스크랩 필드
    scrap_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='scrap_reviews')


class Comment(models.Model):
    content = models.CharField(max_length=255)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms

from .models import VisitorBook, User

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', 'nickname', 'profile_img')


# 회원정보 수정에 필요한 필드 구성
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ('nickname', 'email', 'greetings', 'profile_img')
        excludes = ('password',)

# 일촌평 작성에 필요한 필드
class VisitorBookForm(forms.ModelForm):
    
    class Meta:
        model = VisitorBook
        fields = ['content']


class CustomAuthenticationForm(AuthenticationForm):
    # 현재 라벨 적용안됨 => 불러오는게 잘못된 것 같기도 함
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': '아이디를 입력해주세요'
            }),
            'password': forms.TextInput(attrs={
                'placeholder': '비밀번호를 입력해주세요'
            }),
        },
        labels = {
            'username': '아이디',
            'password': '비밀번호',
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods

from .models import User, SendConnect, VisitorBook
from .forms import CustomUserCreationForm, CustomUserChangeForm, VisitorBookForm, CustomAuthenticationForm

# 영화목록에 이용할 모델 불러오기
from movies.models import Movie
from community.models import Review


def signup(request):
    # 로그인 유저가 회원가입 접근했을 때
    if request.user.is_authenticated:
        # 리다이렉트 시키려면 데이터 넘겨줘야 한다
        return redirect('accounts:firstpage', request.user.username)
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            # 로그인 완료시켜주면 회원가입한 뒤 회원가입 누르면 이동됨 이를 막기 위해 제거
            # auth_login(request, user)
            return redirect('accounts:login') # 일단 이렇게 둠 
    else: 
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


# 로그인이 첫 페이지
def login(request):

    # 로그인 상태로 접근하면 되돌려주기
    if request.user.is_authenticated:
        # 리다이렉트 시키려면 데이터 넘겨줘야 한다
        return redirect('accounts:firstpage', request.user.username)

    else:
        #  POST 요청일 때
        if request.method == 'POST':
            form = CustomAuthenticationForm(request, request.POST)

            if form.is_valid():
                auth_login(request, form.get_user())
                # form에 저장된 user 정보를 꺼내서
                user = form.get_user()
                # 같이 넘겨준 다음 첫 화면을 띄운다
                return redirect('accounts:firstpage', user)
        else:
            form = AuthenticationForm()
            
        context = {
            'form': form,
        }
        return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)

    return redirect('accounts:login')


# 로그인 후 처음으로 만나는 화면
@login_required
def firstpage(request, username):
    # 사용자 정보 가져오기
    host_user = get_object_or_404(get_user_model(), username=username)
    # 사용자 정보를 바탕으로 방명록 글 가져오기
    visitorbooks = VisitorBook.objects.filter(host=host_user.pk).order_by('-pk')
    
    # 스크랩, 영화목록/댓글/작성한글 가져오기

    # 영화리뷰들 가져오기 - 5개만
    reviews = Review.objects.order_by('-pk')[:5]

    # 나와 관련된 정보 불러오기
    # 프로필을 띄운 화면이 메인 페이지가 될 테니까 
    context = {
        'host_user': host_user,
        'visitorbooks': visitorbooks,
        'reviews': reviews,
    }

    return render(request, 'accounts/profile.html', context)


# 내 프로필 정보
@login_required
def mypage(request, username):
    # 해당 페이지의 주인의 정보를 가져와야 한다
    host_user = get_object_or_404(User, username=username)

    # 1. 찜한 영화목록 출력을 위해
    my_movie_list = host_user.mymovie.all()
    # 2. 일촌목록 출력을 위해
    my_friend_list = host_user.connected.all()
    # 3. 내가 스크랩한 글 목록
    my_scrap_list = host_user.scrap_reviews.all()
    
    context = {
        'host_user': host_user,
        'my_movie_list': my_movie_list,
        'my_friend_list': my_friend_list,
        'my_scrap_list': my_scrap_list,
    }

    return render(request, 'accounts/mypage.html', context)



# 내 정보 수정(회원정보 수정)
@login_required
@require_http_methods(['GET', 'POST'])
def myinfo_change(request, username):
        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('accounts:mypage', request.user.username)
        else:
            form = CustomUserChangeForm(instance=request.user)
        
        context ={
            'form': form,
        }
        return render(request, 'accounts/modify_member_info.html', context)


# 스크랩한 글 목록
@login_required
def scrap(request, username):
    # 현재 미니홈피 주인
    host_user = get_object_or_404(User, username=username)
    # 지금 로그인한 사람
    context ={
        'host_user': host_user,
    }
    return render(request, 'accounts/my_scrap.html', context)


# 일촌 목록
@login_required
def linkedin(request, username):
    host_user = get_object_or_404(User, username=username)
    # 조회하는 사람과 프로필 페이지 주인 
    from_user = request.user

    # 전체 신청 중에서 현재 페이지 주인이 take_user에 있으면서 로그인한 사용자가 give_user에 있으면 신청 보낸 상태
    # 이 개수가 존재하면 일촌 신청을 보낸 상태이다
    send_num = SendConnect.objects.filter(give_user=from_user, take_user=host_user).count()
    if send_num:
        is_send = True
    else:
        is_send =False

    # 일촌목록을 보여주려면 전체 리스트를 가져와야한다
    # 1. 신청이 들어온 요청들
    sending_connect = SendConnect.objects.filter(take_user=host_user)

    # 일촌평 작성 폼
    visitorbook_form = VisitorBookForm()
    visitorbooks = VisitorBook.objects.filter(host=host_user).order_by('-pk')
    
    context = {
                'from_user': from_user,
                'host_user': host_user,
                # 요청 보냈는지 여부 확인
                'is_send': is_send,
                # 요청 받은 것 확인
                'sending_connects': sending_connect,
                # 일촌평 작성부분
                'visitorbook_form': visitorbook_form,
                # 작성된 일촌평들
                'visitorbooks': visitorbooks,
    }
    
    return render(request, 'accounts/connection_list.html', context)


# 일촌 신청 보내기
@login_required
def send_connected(request, username):
    # 로그인한 유저인지 확인
    if request.user.is_authenticated:
        # 1. 현재 로그인된 사용자 정보를 가져온다(from)
        from_user = request.user
        # 2. 현재 접속한 페이지의 주인 정보를 가져온다(to)
        host_user = get_object_or_404(User, username=username)

        # 2-1. 요청자 != 나일 때
        if from_user != host_user:

            # 3. 요청을 보내고 연결해준다(POST)
            send_connecting = SendConnect(
                give_user = from_user,
                take_user = host_user, 
                )
            # 모델에 저장
            send_connecting.save()

            # 요청을 보냈으니 불리안을 True로
            is_send = True


            # 넘겨줄 데이터
            context = {
                'from_user': from_user,
                'host_user': host_user,
                'is_send': is_send,
            }

        return render(request, 'accounts/connection_list.html', context)
    
    else:
        return render(request, 'accounts/login.html')


# 일촌 수락하기 - 수락할(take) 사람, 일촌 신청 테이블에서 삭제(pk)
# 신청당한사람/연결/신청보낸사람
@login_required
def connected_complete(request, to_username, from_username, send_connect_pk):
    # POST
    # 1. 일촌 수락버튼을 클릭한다 => connected 필드 True로 변경
    give_user = get_object_or_404(get_user_model(), username=from_username)
    take_user = get_object_or_404(get_user_model(), username=to_username)

    take_user.connected.add(give_user)

    # 2. 일촌 신청 테이블에서 삭제한다.
    send_connect = get_object_or_404(SendConnect, pk=send_connect_pk)
    send_connect.delete()

    return redirect('accounts:linkedin', take_user.username)


# 일촌평 작성 - 페이지 주인(아이디) / 사용자(아이디)
@login_required
@require_http_methods(['GET', 'POST'])
def visitor_book_create(request, host, writer):
    # POST 요청일 때
    host_user = get_object_or_404(get_user_model(), username=host)

    if request.method == 'POST':
        form = VisitorBookForm(request.POST)

        if form.is_valid():
            # 외래키 연결
            visitor_book = form.save(commit=False)
            visitor_book.host = host_user
            visitor_book.writer = request.user
            visitor_book.save()

            return redirect('accounts:linkedin', host)

    else:
        linkedin(request, host)


# 내 영화목록 조회 - 추가한 영화 목록과 검색기능(DB)
@login_required
def my_movie_list(request, username):

    # 해당 페이지의 주인의 정보를 가져와야 한다
    host_user = get_object_or_404(User, username=username)

    # 1. 영화 전체 리스트를 가져온다
    movies = Movie.objects.all()
    # 2. 검색어가 있을 때는 해당 쿼리셋도 가져온다
    search_movie = request.GET.get('search_movie')
    
    host = get_object_or_404(User, username=username)
    # 5. 나의 영화리스트 정보 가져오기
    
    # 검색한 뒤인지 검색안했는지 판별할 bool
    is_search = False

    if search_movie:
        search_movie_list = movies.filter(title__icontains=search_movie)
        is_search = True

    else:
        search_movie_list = '결과없음'
    # 4. 검색 결과에서 클릭을 하면 내가본영화 모델에 들어간다

    # 3. 담아서 넘겨준다. -username (내 영화리스트에 넣기 위해 필요)
    context = {
        'search_movie': search_movie,
        'search_movie_list': search_movie_list,
        'username': username,
        'host': host,
        'host_user': host_user,

    }
    return render(request, 'accounts/my_movie_list.html', context)


# 내 영화목록에 추가
@login_required
def add_mymovie_list(request, username, movie_pk):
    # 넘겨받은 데이터를 바탕으로 모델에 저장 - 존재하지 않을 때
    user = get_object_or_404(User, username=username)
    movie = get_object_or_404(Movie, pk=movie_pk)
    if not user.mymovie.filter(pk=movie_pk).exists():  
        user.mymovie.add(movie)
    return redirect('accounts:my_movie_list', username)


# 내 영화목록에서 제거
@login_required
def remove_mymovie_list(request, username, movie_pk):
    user = get_object_or_404(User, username=username)
    movie = get_object_or_404(Movie, pk=movie_pk)
    # 존재하면 빼주자
    if user.mymovie.filter(pk=movie_pk).exists():  
        user.mymovie.remove(movie)
    return redirect('accounts:my_movie_list', username)

accounts/templates/accounts/_middle_reviews_and_ad.html
{% load static %}
{% block middle %}
<div padding="5px">
		<table width="550">
			<tr>
				<th>
					<!-- 가운데 상단 제목 -->
					<br>
					<font style="font-size:11pt;"><strong><p class="text-center">{{ host_user.username }}님의 미니홈피</p></strong></font>
				</th>
			</tr>
			
			<tr class="updated_news">
				<!-- 영화리뷰들(업데이트 된) -->
				<td width="250" >
					{% for review in reviews %}
					<div class="review-list">
							<a class="text-primary" href="{% url "community:detail" review.pk %}">
							NEW {{ review.title }}
							</a>
					</div>{% endfor %}
					
				</td>
				<td width="10"></td>

				<!-- 내가 관련된 게시물들(가운데 상단 오른쪽부분) -->
				<td class="my_reviews">  	
					<table width="350">
						<tr><strong><p>나의 활동</p><strong></tr>
						<tr>

							<td><p style="font-size:11pt;">나의 작성글 ({{ host_user.review_set.all|length }})</p><br></td>
							<td><p style="font-size:11pt;">나의 댓글 ({{ host_user.comment_set.all|length }})</p><br></td>
						</tr>
						<tr>
							<td><p style="font-size:11pt;">나의 스크랩 ({{ host_user.scrap_reviews.all|length }})</p><br></td>
							<td><p style="font-size:11pt;">나의 찜목록 ({{ host_user.mymovie.all|length }})</p><br></td>
						</tr>
									
					</table>
				</td>
			</tr>
		</table>
		
				<br/>

				<table class="set-middle" bgcolor="#DBDBDB" width="450">

					<tr>
						<td>  
							<!-- 가운데 미니룸 이미지 -->
							<img width="550" height="300"  src="{% static "/img/middle_img4.jpg" %}" alt="">
						</td>
					</tr>
				</table>

				<!-- 가운데 하단 일촌평 -->
				<hr>
				<div style="text-align:right;">
				<!-- 접속자 == 프로필 주인 -->
				{% if request.user == host_user %}
					<a type="button" class="logout_btn" width="85" height="50" border="5" alt="일촌평" value="일촌평" href="{% url 'accounts:linkedin' host_user.username %}">일촌평 보기</a><br><br>
				</div>
				<!-- 내 미니홈피가 아닐때는 작성가능 -->
				{% else %}
					<a type="button" class="logout_btn" width="85" height="50" border="5" alt="일촌평" value="일촌평" href="{% url 'accounts:linkedin' host_user.username %}">일촌평 작성</a><br>
					</div>
				{% endif %}
				<!-- 방명록 글 가져오기 for로 -->
				{% for book in visitorbooks %}
					<!-- 프로필 사진 -->
					<div style="border:1px solid #C4CACD;margin:10px">
						<div style="border:1px solid #C4CACD;background-color:#C4CACD;display:flex;justify-content:space-around; ">
							<div>작성자:{{ book.writer.nickname }}</div> 
							<font style="font-size:9pt;">
							<div>작성 시각:{{ book.created_at }}</div></font>
						</div>
						<div style="display:flex;display-direction:row;">
							<div style="border:1px solid #C4CACD;width:110px;">
								<!-- 포스터 가지고 있다면 -->
								{% if book.writer.profile_img %}
								<img src="{{ book.writer.profile_img.url }}" alt="" width="109px" height="148px">
								{% else %}
								<!-- 포스터 없을 때 -->
								<img src="{% static "/img/empty_profile.png" %}" alt="" width="109px" height="148px">
								{% endif %}
							</div>
							<div style="width:400px;">
							{{ book.content }}</div>
						</div>
					</div>
				<br>
      	{% endfor %}
</div>

{% endblock middle %}
	



						

accounts/templates/accounts/connection_list.html
{% extends 'base.html' %}

{% load static %}

{% block left %}
  {% include 'accounts/_left_profile.html' %}
{% endblock left %}
{% block middle %}
  <br>
  <font style="font-size:14pt;"><strong><p class="text-center">일촌 리스트</p></strong></font>
    <!-- 내가 내 일촌목록 볼 때 -->
 <div class="movie-list-form"> 
  {% if from_user == host_user %}
      <!-- 내가 내 일촌목록 볼 때 -->
      <font style="font-size:10pt;"><p>{{ host_user.nickname }}님의 일촌 ({{ host_user.connected.all|length }})</p></font>
      <!-- 일촌 목록 보여주기 -->
      <div style="border:1px solid #C4CACD">
      {% for friend in host_user.connected.all %}
      <ul>{{ friend }}</ul>
      {% endfor %}
      </div>
      
        {% if sending_connects %}
          <font style="font-size:10pt;"><p>도착한 요청</p></font>
          {% for send in sending_connects %}
            <form action=""></form>
            <form action="{% url "accounts:connected_complete" host_user.username send.give_user send.pk %}">
              {% csrf_token %}
              <font style="font-size:8pt;">{{ send.give_user }}님이 일촌을 요청했습니다.</font>
              <input type="submit" value="수락">
            </form>
          {% endfor %}
        {% else %}
          <font style="font-size:10pt;"><p>들어온 일촌 요청이 없습니다🙇🏼‍♂️</p></font>
        {% endif %}
      <!-- 내꺼여도 일촌평 볼 수 있어야함 -->
      {% for book in visitorbooks %}
        <div style="border:1px solid #C4CACD;margin:10px">
          <div style="border:1px solid #C4CACD;background-color:#C4CACD;display:flex;justify-content:space-around; ">
          <div>작성자:{{ book.writer }}</div> 
          <font style="font-size:9pt;"><div>작성 시각:{{ book.created_at }}</div></font>
          </div>
          <div style="display:flex;display-direction:row;">
            <div style="border:1px solid #C4CACD;width:130px;">
              <!-- 포스터 -->
              <img src="{{ book.writer.profile_img.url }}" alt="" width="129px" height="148px">
            </div>
            <div style="width:400px;">{{ book.content }}</div>
          </div>
        </div>
        <br>
      {% endfor %}
    <!-- 일촌일때 보여줄 메세지 -->
    {% elif from_user in host_user.connected.all %}
      <font style="font-size:12pt;"><p>{{ host_user }}님의 일촌인 {{ from_user }}님 반가워요👋🏼</p>
      <!-- 일촌평 남길 수 있는 부분 -->
      <form action=""></form>
      <form action="{% url "accounts:visitor_book_create" host_user from_user %}" method="POST">
        {% csrf_token %}
        <p><strong>방명록 작성하기</strong></p>
          {{ visitorbook_form.content }}
        <input class="logout_btn" type="submit" value="작성">
      </form>
      <hr>
      <br>
      <!-- 일촌평 보여줄 부분 -->
      <!-- 이부분에 저번에 보여준 것처럼 작성자랑 프로필사진 내용 느낌으로 가면 좋을 것 같음-->
      <p><strong>{{ host_user }}님께 한마디 남겨보세요✍🏼</strong></p>
        {% for book in visitorbooks %}
          <div style="border:1px solid #C4CACD;margin:10px">
            <div style="border:1px solid #C4CACD;background-color:#C4CACD;display:flex;justify-content:space-around; ">
            <div>작성자:{{ book.writer }}</div> 
            <font style="font-size:9pt;"><div>작성 시각:{{ book.created_at }}</div></font>
            </div>
            <div style="display:flex;display-direction:row;">
              <div style="border:1px solid #C4CACD;width:110px;">
                <!-- 포스터 있을때 -->
                {% if book.writer.profile_img %}
								<img src="{{ book.writer.profile_img.url }}" alt="" width="109px" height="148px">
								{% else %}
								<!-- 포스터 없을 때 -->
								<img src="{% static "/img/empty_profile.png" %}" alt="" width="109px">
								{% endif %}
              </div>
              <div style="border:1px solid #C4CACD;width:400px;">{{ book.content }}</div>
            </div>
          </div>
          <br>
        {% endfor %}
    
      
    <!-- 일촌은 아니지만 일촌 신청을 보냈을 때 -->
    {% elif is_send %}
      <p>일촌이 아니지만 요청은 보냈어요!</p>
    <!-- 일촌이 아니고 요청도 안보냈을 때 -->
    {% else %}
      <p>나와 일촌이 아닙니다.</p>
      <!-- 일촌 신청 버튼 -->
      <form action=""></form>
      <form action="{% url "accounts:send_connected" host_user.username %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="일촌신청하기!">
      </form>
</font>
    {% endif %}
    <hr>
    <a class="logout_btn submit-btn" href="{% url "accounts:mypage" request.user %}">뒤로가기</a>
</div>
  
{% endblock %}